before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
dockers:
  - image_templates:
      - "itzg/grpc-authenticated-greeter"
      - "itzg/grpc-authenticated-greeter:{{ .Tag }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .ShortCommit }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
    - '^misc:'
